name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.3'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: flake8
      run: |
        make flake8
    - name: isort and yapf
      run: |
        make py-format
    - name: cpplint
      run: |
        make cpplint
    - name: clang-format
      run: |
        make clang-format
    - name: buildifier
      run: |
        make buildifier
    - name: addlicense
      run: |
        make addlicense
    - name: mypy
      run: |
        make mypy
    - name: docstyle
      run: |
        make docstyle
    - name: spelling
      run: |
        make spelling
