name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.16.0'
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: ngrok
      run: |
        whoami
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYviCJ4Mn5flYXnj3pvJmVcFCFfWZfiJx4MZtBHi0MJv9aVHMqb1Sw/xH/cUx5hE++o89UpsEPcLafPkZ4Yg/ZP1Yc9LGehDIL81L8CwiYl38dreyd8PM+t5d58GIt6Dr8ubjxO03JiTsgMb8wMCXtkKkcUFJ+GXviW9JUPgLP7T05mMJO8VNe05ibnnodXUh8bRCybLDm9IQgKEY1Qh3Mwztkg+5H6d+YLL1ZwdUyIk8o5MmxIcCi8u/+tjB3RBIFJ3wShFGVqeHHJVwda6VL6fb3igB2uSVOJFsQMO5ulG21SepSWjygW+Qfr90rDX9nFMw9E6GJfLSAnvGR53zv root@localhost.localdomain" >> ~/.ssh/authorized_keys
        chmod 664 ~/.ssh/authorized_keys
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar xzvf ngrok-v3-stable-linux-amd64.tgz
        ./ngrok config add-authtoken 2E9NKZXT714eRzvy2rNRONkVFgr_2uC2GrGw39iYYix8kNasU
        ./ngrok tcp 22
    - name: flake8
      run: |
        make flake8
    - name: isort and yapf
      run: |
        make py-format
    - name: cpplint
      run: |
        make cpplint
    - name: clang-format
      run: |
        make clang-format
    - name: buildifier
      run: |
        make buildifier
    - name: addlicense
      run: |
        make addlicense
    - name: mypy
      run: |
        make mypy
    - name: docstyle
      run: |
        make docstyle
    - name: spelling
      run: |
        make spelling
