name: Release PyPI Wheel

on: [push, pull_request]

jobs:
  release:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Build wheel
      run: |
        make docker-release
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: wheel
        path: wheelhouse/
