name: Release PyPI Wheel

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - main

jobs:
  release:
    runs-on: ubuntu-latest
    container: trinkle23897/envpool-release:2022-12-27-24e7aef
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        pwd
        env
        whereis pyenv
        which pyenv
        echo "=== /root/.pyenv/versions"
        ls /root/.pyenv/versions
        echo "=== /root/.pyenv/shims"
        ls /root/.pyenv/shims
        echo "=== /github/home/.pyenv"
        ls /github/home/.pyenv
        echo "=== /github/home/.pyenv/versions"
        ls /github/home/.pyenv/versions
        echo "=== /github/home/.pyenv/shims"
        ls /github/home/.pyenv/shims

        PYENV_DEBUG=1 /root/.pyenv/bin/pyenv global ${{ matrix.python-version }}-dev
        echo "==="
        env
        whereis pyenv
        which pyenv
    - name: Build
      run: |
        make pypi-wheel
        pip3 install wheelhouse/*.whl --force-reinstall
    - name: Test
      run: |
        make release-test
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: wheel
        path: wheelhouse/
