name: Release PyPI Wheel

# on: [push, pull_request]
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    container: trinkle23897/envpool-release:2022-12-29-03c3d95
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        ln -sf /root/.cache $HOME/.cache
        ln -sf /root/.pyenv $HOME/.pyenv
        pyenv global ${{ matrix.python-version }}-dev
    - name: Build
      run: |
        make pypi-wheel
        pip3 install wheelhouse/*.whl --force-reinstall
    - name: Test
      run: |
        make release-test
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: wheel
        path: wheelhouse/
