name: Bazel Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.2'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # make bazel-install
    - name: Build
      run: |
        make bazel-build BAZELOPT="--remote_cache=http://bazel-cache.sail:8080"
    - name: Test
      run: |
        make bazel-test BAZELOPT="--remote_cache=http://bazel-cache.sail:8080"
