name: Bazel Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: trinkle23897/envpool:2022-12-25-bf842a5
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        ls /usr/local/cuda
        df -h
        pwd
    - name: Test
      run: |
        bazel build //envpool/classic_control --config=test
    - name: Run clang-tidy
      run: |
        ls ~/.cache/bazel/*
