name: Bazel Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: trinkle23897/envpool:2022-12-25-bf842a5
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
    - name: Cache ~/.cache folder
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: envpool-cache-${{ runner.os }}
    - name: Test
      run: |
        make bazel-test
    - name: Run clang-tidy
      run: |
        make clang-tidy

