name: Bazel Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: [self-hosted, Linux, X64, Test]
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.3'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Test
      run: |
        make bazel-test BAZELOPT="--remote_cache=http://bazel-cache.sail:8080"
    - name: Run clang-tidy
      run: |
        make bazel-clang-tidy BAZELOPT="--remote_cache=http://bazel-cache.sail:8080"
