name: Bazel Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: [self-hosted, Linux, X64, Test]
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
    - name: Test
      run: |
        make bazel-test
    - name: Run clang-tidy
      run: |
        make clang-tidy
